Properly handle storage permission on 8.1+
Deletescape-Media/Lawnchair pull request #1145
Opened 2018-02-20 18:41 UTC by deletescape

Prompt the user for the Storage permission with an explaination and disable blur without it to prevent crashes.

@divadsn a quick look over this would be appreciated

Manually tested on RR O 8.1 in all ways I was able to imagine 😉

2018-02-20 18:43 UTC, divadsn commented
@deletescape added to my list, I will be back next Sunday.

2018-02-20 18:45 UTC, msfjarvis approved these changes
LGTM

2018-02-20 18:45 UTC, MSF-Jarvis commented on app/src/main/java/ch/deletescape/lawnchair/Launcher.java
> +                        .setMessage(R.string.content_storage_permission_required).setPositiveButton(android.R.string.ok, listener)
nit: line length

2018-02-21 13:42 UTC, divadsn requested changes
Storage permissions are also required for extracting the accent color for the dock background, which is also enabled by default and causes crashes on Oreo 8.1

2018-02-22 18:38 UTC, deletescape commented
@divadsn updated the PR according to your comment, was able to reproduce after clearing data

2018-02-22 18:47 UTC, divadsn commented
Pls fix codacy @deletescape

2018-02-24 23:05 UTC, divadsn commented
FFS STOP IT TRAVIS, YOU AREN'T SUPPOSED TO BE TRIGGERED ON PR ANYMORE.

2018-02-25 07:14 UTC, TheComputerGuy96 commented
Travis, just REEEEEEEEEEEEEEEEE

2018-02-25 17:26 UTC, divadsn approved these changes

2018-02-25 21:57 UTC, merged