Allow icon pack dashboards to change icon pack externally
Deletescape-Media/Lawnchair pull request #2392
Opened 2021-12-27 12:52 UTC by DarkionAvey

Hello!

This is a port from legacy Lawnchair, but with a new intent name to match the new package name of the app '`app.lawnchair`'

Check out the video below to see how it looks, or download the test icon pack (attached) to test it yourself 

How to call:
```
        val lawnchair = Intent("app.lawnchair.APPLY_ICONS", null)
        lawnchair.putExtra("packageName", packageName)
        startActivity(lawnchair)
```
[(test icon pack) app-release.zip](https://github.com/LawnchairLauncher/lawnchair/files/7780210/app-release.zip)

Tested on Android 12, but I assume it works fine on older versions because the UI is made in Compose

https://user-images.githubusercontent.com/11511782/147472892-193dd5ff-4490-4301-8c0e-bf62573741dc.mp4

2021-12-28 05:32 UTC, paphonb requested changes

2021-12-28 05:32 UTC, paphonb commented on lawnchair/src/app/lawnchair/ui/preferences/ApplyIconPackActivity.kt
> +import androidx.compose.material.Surface
Please use material3 Surface instead

2021-12-28 05:32 UTC, paphonb commented on lawnchair/src/app/lawnchair/ui/preferences/ApplyIconPackActivity.kt
> +                                shape = RoundedCornerShape(topStart = 25.dp, topEnd = 25.dp),
Should be 24dp

2021-12-28 05:32 UTC, paphonb commented on lawnchair/src/app/lawnchair/ui/preferences/ApplyIconPackActivity.kt
> +                                            InvalidIconPackPlaceholder(
I think we should just finish the activity in this case

2021-12-28 05:32 UTC, paphonb commented on lawnchair/src/app/lawnchair/ui/preferences/ApplyIconPackActivity.kt
> +                    painter = rememberImagePainter(bitmap),
I think we can do `bitmap = bitmap.asImageBitmap()` instead of using Coil

2021-12-28 05:32 UTC, paphonb commented on lawnchair/src/app/lawnchair/ui/preferences/ApplyIconPackActivity.kt
> +                shape = CircleShape,
Let's keep the original icon shape instead of cropping to a circle

2021-12-28 05:32 UTC, paphonb commented on lawnchair/src/app/lawnchair/ui/preferences/ApplyIconPackActivity.kt
> +        HorizontalSpacer(height = 8.dp)
I think 16 might look better

2021-12-28 05:32 UTC, paphonb commented on lawnchair/src/app/lawnchair/ui/preferences/ApplyIconPackActivity.kt
> +        CircularIcon(bitmap = iconPackIcon)
Add some space above the icon

2021-12-28 05:32 UTC, paphonb commented on lawnchair/src/app/lawnchair/ui/preferences/ApplyIconPackActivity.kt
> +        var iconPacksPreference by preferenceManager().iconPackPackage.getAdapter()
You don't need the adapter here. The pref entry has a `set` method.

2021-12-29 16:42 UTC, DarkionAvey commented
I implemented all of your feedback comments except for finishing the activity when the icon pack is invalid. I don't know how to achieve that while `iconPacks.collectAsState()` is emitting values and causing re-composition. The only thing I can think of is to implement a quick icon pack validation by checking the package's intents against `app.lawnchair.ui.preferences.PreferenceViewModelKt#iconPackIntents` and short-circuiting if the icon pack is invalid. What do you suggest? 
Thanks

2021-12-30 04:07 UTC, HLA55 commented
###

2021-12-30 06:32 UTC, paphonb commented
> I implemented all of your comments except for finishing the activity when the icon pack is invalid. I don't know how to achieve that while re-composition is triggered. The only thing I can think of is to implement a quick icon pack validation by checking the package's intents against `app.lawnchair.ui.preferences.PreferenceViewModelKt#iconPackIntents` and short-circuiting if the icon pack is invalid, all before `setContent`. What do you suggest?
> Thanks

I think you can just call `finish()` in a side effect block, since the Activity would still be in scope

2022-01-03 22:36 UTC, DarkionAvey commented
> > I implemented all of your comments except for finishing the activity when the icon pack is invalid. I don't know how to achieve that while re-composition is triggered. The only thing I can think of is to implement a quick icon pack validation by checking the package's intents against `app.lawnchair.ui.preferences.PreferenceViewModelKt#iconPackIntents` and short-circuiting if the icon pack is invalid, all before `setContent`. What do you suggest?
> > Thanks
> 
> I think you can just call `finish()` in a side effect block, since the Activity would still be in scope

So I experimented with different ways, and I found that this (in the last commit) is the simplest one. 
Let me know what you think. 

Also, there's a little visual disturbance because `backgroundDimEnabled` is set to true so the window will dim then go back to normal after few seconds if the icon pack is invalid. I think it's OK since the user won't end up seeing this anyway

2022-01-15 18:28 UTC, DarkionAvey commented
Any updates on whether this will be implemented or not?

2022-01-31 21:34 UTC, patrykmichalik commented
Hello, @DarkionAvey! Thanks for your interest in contributing, and sorry for the wait. We’d be happy to merge this pull request with some changes, but because you appear to have deleted the Lawnchair fork on which this PR is based, no changes can be suggested or made. Would you be able to create a new Lawnchair fork, copy the changes from this pull request to it, and open a new pull request? I’ll then be able to suggest some changes. Thanks in advance, and sorry once more for the delay.

2022-02-13 23:41 UTC, Shine19958 commented
Pull

2022-02-14 08:31 UTC, closed without merging