Move all preference defaults to resources
Deletescape-Media/Lawnchair pull request #2540
Opened 2022-04-17 07:36 UTC by erfanoabdi

Having default values in resources helps custom ROMs to setup desired config by creating "Runtime Resource Overlays (RROs)" on system image

On 9 version we had some prefs on res: https://github.com/LawnchairLauncher/lawnchair/blob/9-dev/lawnchair/res/values/config.xml

Sample of RRO on POSP (LawnConf): https://github.com/PotatoProject/vendor_potato/tree/baked-release/packages/overlays/Common/LawnchairConfig

2022-04-19 15:06 UTC, inecek approved these changes

2022-04-20 06:38 UTC, patrykmichalik requested changes
Thanks for your interest in contributing! Just two small things. First, I’d suggest removing the extra empty line in `config.xml`. Second, how about creating a `resourceProvider` field in `PreferenceManager2` rather than repeating `DynamicResource.provider(context)` each time a `ResourceProvider` instance is needed?

2022-04-20 06:38 UTC, patrykmichalik commented on lawnchair/res/values/config.xml
> +
```suggestion
```

2022-04-20 10:26 UTC, yasandev commented
Should be ok now. @patrykmichalik

2022-04-23 13:35 UTC, patrykmichalik approved these changes

2022-04-23 13:37 UTC, merged

2022-04-23 13:37 UTC, patrykmichalik commented
Thank you!