Persian Calendar on Glance
Deletescape-Media/Lawnchair pull request #2637
Opened 2022-05-23 07:06 UTC by yasandev

Adds Persian Calendar support to Glance + A system to manually reload the date content on Glance as it was not previously possible.

The changes also allow other contributors to add their own local calendar system to the project easily.

The Persian Date is always shown in Farsi for now but I will create an additional PR to make the Persian Date respect the language of the device later on as the library used for the Persian Date does not support this feature (yet).

2022-05-23 07:47 UTC, yasandev commented
Sorry for the force pushes, just a few small adjustments.

2022-05-24 07:20 UTC, yasandev commented
- Improved how `IcuDateTextView.kt` listens to calendar changes.
- Smartspace custom calendar is now experimental & the default value is used when the experimental feature is disabled.
- Default calendar system for Farsi (Iran) is set to Persian in resources.

@paphonb

2022-05-24 08:21 UTC, paphonb approved these changes

2022-05-24 08:42 UTC, ghost requested changes

2022-05-24 08:42 UTC, ghost commented on lawnchair/src/app/lawnchair/smartspace/model/SmartspaceCalendar.kt
> +        }
An expression body could be used here for conciseness.

```suggestion
        fun fromString(value: String): SmartspaceCalendar =  when (value) {
            "persian" -> Persian
            else -> Gregorian
        }
```

2022-05-24 08:42 UTC, ghost commented on AndroidManifest-common.xml
> +        tools:replace="android:label">
Just to confirm, is the addition of `tools:replace="android:label"` intentional? I’m unfamiliar with this attribute.

2022-05-24 08:42 UTC, patrykmichalik commented on lawnchair/src/app/lawnchair/smartspace/IcuDateTextView.kt
> +    }
I’d suggest avoiding the use of not-null assertion here.

```suggestion
    private fun getTimeTextPersian(updateFormatter: Boolean): String {
        val formatter = formatterPersian.takeIf { updateFormatter.not() } ?: PersianDateFormat(
            context.getString(R.string.smartspace_icu_date_pattern_persian),
            PersianDateFormat.PersianDateNumberCharacter.FARSI,
        ).also { formatterPersian = it }
        return formatter.format(PersianDate(java.lang.Long.valueOf(System.currentTimeMillis())))
    }
```

2022-05-24 08:42 UTC, patrykmichalik commented on lawnchair/src/app/lawnchair/smartspace/IcuDateTextView.kt
> +        return formatterGregorian!!.format(java.lang.Long.valueOf(System.currentTimeMillis()))
I’d suggest avoiding the use of not-null assertion here.

```suggestion
        val formatter = formatterGregorian.takeIf { updateFormatter.not() }
            ?: DateFormat.getInstanceForSkeleton(
                context.getString(R.string.smartspace_icu_date_pattern_gregorian),
                Locale.getDefault()
            ).also { formatterGregorian = it }
        return formatter.format(java.lang.Long.valueOf(System.currentTimeMillis()))
```

2022-05-24 09:08 UTC, yasanglass commented on AndroidManifest-common.xml
> +        tools:replace="android:label">
It is. It basically tells gradle to use the `android:label` value from this manifest file and not from a conflicting one from the Persian Date library. Basically, it won't build with that dependency if this line is not added here.

2022-05-24 09:29 UTC, yasanglass commented on lawnchair/src/app/lawnchair/smartspace/IcuDateTextView.kt
> +        return formatterGregorian!!.format(java.lang.Long.valueOf(System.currentTimeMillis()))
This is the exact original code and I just tried to not modify it and keep the same format even for the Persian Date function. It's now fixed on the new force push.

2022-05-24 09:30 UTC, yasandev commented
@patrykmichalik Should be ok now.

2022-05-24 09:42 UTC, patrykmichalik commented on AndroidManifest-common.xml
> +        tools:replace="android:label">
Got it. Thanks!

2022-05-24 09:47 UTC, patrykmichalik commented on lawnchair/src/app/lawnchair/smartspace/IcuDateTextView.kt
> +        return formatterGregorian!!.format(java.lang.Long.valueOf(System.currentTimeMillis()))
Ah, sorry, I didn’t notice that you’d used the preexisting code. If I had, I wouldn’t have requested this change, as it’s not entirely related to the pull request. I would’ve probably made it myself after the merge. But if you’ve already applied it, I don’t think it hurts to keep it. My apologies for the error.

2022-05-24 09:48 UTC, patrykmichalik approved these changes

2022-05-24 12:30 UTC, merged