More Accessible Home Screen Lock Toggle
Deletescape-Media/Lawnchair pull request #2664
Opened 2022-05-29 11:18 UTC by yasandev

Adds Home Screen lock toggle to the home screen's pop-up menu to make it more accessible (Closes #1711).

This is meant to be merged after #2663 & will be updated if #2663 is modified. Only c49b78c631327a3e8917d18da97f93ea82d05388 is new on top of the changes on #2663.

2022-05-29 13:28 UTC, paphonb commented
I think it could be hidden in the unlocked state to keep it clean because it probably won't be used often.

2022-05-30 06:03 UTC, yasandev commented
@paphonb I can just add a simple switch for it but I suppose I should make a preference group for Lock in that case so it looks cleaner.

2022-05-30 07:46 UTC, yasandev commented
I added the new toggle below the lock switch but I believe the whole Home Screen preferences could use a bit of cleaning up.

2022-05-31 06:06 UTC, yasandev commented
I updated the code to use the new `setBlocking()` function from @patrykmichalik's PreferenceManager v1.0.7 instead of the previous way as it's much better in every aspect.

A `toggleBlocking()` function would make it even cleaner.

2022-05-31 10:19 UTC, patrykmichalik commented
I believe @paphonb’s suggestion is for the button to be visible when the home screen is locked, and gone when the home screen is unlocked. But let’s wait for his input.

2022-05-31 10:26 UTC, yasandev commented
Uh, a one-way toggle button wouldn't be that useful in my opinion, especially since this is meant for accessibility. Maybe I can add two separate switches? One toggles the ***lock*** button and the other one toggles the ***unlock*** button. But I guess then it would be too complicated idk.

2022-06-06 07:40 UTC, patrykmichalik requested changes
Just one small suggestion from my end.

2022-06-06 07:40 UTC, patrykmichalik commented on lawnchair/res/values/strings.xml
> +    <string name="home_screen_lock_toggle_from_home_popup">Toggle Lock Button On Pop-up</string>
```suggestion
    <string name="home_screen_lock_toggle_from_home_popup">Show Lock Button in Pop-Up</string>
```

2022-06-06 07:49 UTC, yasandev commented on lawnchair/res/values/strings.xml
> +    <string name="home_screen_lock_toggle_from_home_popup">Toggle Lock Button On Pop-up</string>
Fixed on the new force push.

2022-06-06 08:02 UTC, patrykmichalik approved these changes

2022-06-06 08:02 UTC, merged

2022-06-06 08:02 UTC, patrykmichalik commented
Thanks, @yasandev and @DariaHamrahPaytakht!