add proper icon and description for Gestures
Deletescape-Media/Lawnchair pull request #2684
Opened 2022-06-05 13:42 UTC by marshmello61

Signed-off-by: Mayur <ultramayur123@gmail.com>

2022-06-10 14:25 UTC, ghost requested changes
Hello! Thanks for your interest in contributing. The icons used on the main page of the Settings screen have rounded stroke terminals, but the stroke terminals of `ic_gestures.xml` appear to be sharp. I would suggest using [this icon](https://fonts.google.com/icons?selected=Material%20Icons%20Round%3Agesture%3A).

2022-06-11 14:51 UTC, marshmello61 commented
I see, thanks for reviewing. Will force push with needed change

2022-06-11 15:52 UTC, marshmello61 commented
> Hello! Thanks for your interest in contributing. The icons used on the main page of the Settings screen have rounded stroke terminals, but the stroke terminals of `ic_gestures.xml` appear to be sharp. I would suggest using [this icon](https://fonts.google.com/icons?selected=Material%20Icons%20Round%3Agesture%3A).

Done

2022-06-18 15:09 UTC, patrykmichalik requested changes
It looks like the icon I linked in my last review has a non-standard stroke width, so I’ve created a similar one with the typical stroke width of 2 px. Below is a suggestion you can apply. Apologies for the oversight from my end.

2022-06-18 15:09 UTC, patrykmichalik commented on lawnchair/res/drawable/ic_gestures.xml
> +</vector>
```suggestion
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <path
        android:fillColor="#00000000"
        android:pathData="M4,6C4,4.5 6,3 7.5,4.5C10.5,7.5 2.5,12.5 5,15C7.5,17.5 11,9.5 14.5,9.5C19,9.5 18,20 14,20C10,20 11,12 20,13.5"
        android:strokeWidth="2"
        android:strokeColor="#000000"
        android:strokeLineCap="round"
        android:strokeLineJoin="round" />
</vector>
```

2022-06-18 16:49 UTC, patrykmichalik approved these changes

2022-06-18 16:49 UTC, merged

2022-06-18 16:49 UTC, patrykmichalik commented
Thanks, @marshmello61!