Sesame Search Provider
Deletescape-Media/Lawnchair pull request #2687
Opened 2022-06-06 05:32 UTC by yasandev

This PR currently just contains the removed commit from #2672 that added Sesame search provider (on top of the commits in #2672). I will adjust the code based on the discussion made on #2672 and this draft PR is only created for further discussion around the topic while it's being worked on.

2022-06-06 10:39 UTC, yasandev commented
Ready for review! As discussed with @patrykmichalik, the core functionality is ready & it just requires some UI/UX changes which will be done by the core Lawnchair team instead of me. 

Thanks, @patrykmichalik!

2022-06-06 14:38 UTC, ghost requested changes
Hello! Here’s one minor suggestion.

2022-06-06 14:38 UTC, ghost commented on lawnchair/src/app/lawnchair/qsb/providers/QsbSearchProvider.kt
> +    }
I would suggest using the `PackageManager#isPackageInstalled` extension function here. See lines 137 and 138 of `IconPackPreferences.kt` for an example.

2022-06-07 07:09 UTC, yasandev commented on lawnchair/src/app/lawnchair/qsb/providers/QsbSearchProvider.kt
> +    }
Done!

2022-06-08 14:38 UTC, patrykmichalik commented
Thanks, @yasandev and @DariaHamrahPaytakht! As we’ve discussed, I’ll be merging the changes from this pull request into a feature branch.

2022-06-08 14:39 UTC, merged