Experimental feature - Transparent Background
Deletescape-Media/Lawnchair pull request #3011
Opened 2022-10-09 18:56 UTC by naveenccmsd

## Description

#3003 
It would be nice to have an option to make icon background transparent when themed icons (with Lawnicons) used.

Fixes #(issue) 

## Type of change

:x: General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
 :white_check_mark: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

Impementation step.

- Added switch to enable `Transparent Background` as Experimental option.
- If `Transparent Background` Enabled background would be set to transparent.
     - No other change applied to dark mode
     - Previous Icon color will be odd or to transparent in light theme without icon background. So composite color will be calculared for current Icon color and same will be applied.

2022-10-10 10:44 UTC, naveenccmsd commented
[3003#issuecomment-1273121884](https://github.com/LawnchairLauncher/lawnchair/issues/3003#issuecomment-1273121884)

2022-10-11 14:43 UTC, kahanzammi commented
Tested build 1181 on Android 13. Lawnchair freezes as soon as themed icons enabled - without and without enabling the experiment feature. Unable to capture any logs. Screenshot below.

![Screenshot_20221011-171757](https://user-images.githubusercontent.com/105884763/195122703-f70476a6-6d36-4f0f-994b-57c4b41a0522.png)

2022-10-11 14:57 UTC, naveenccmsd commented
Even I'm facing same issue from build 1181 but didn't face such issue from latest changes ,

2022-10-11 14:59 UTC, naveenccmsd commented
Please wait for latest build to approved and executed

2022-10-11 18:40 UTC, kahanzammi commented
Tested latest, works fine. I believe currently only black icons are supported.

![Screenshot_20221011-223332](https://user-images.githubusercontent.com/105884763/195172991-eca47cb3-f7a7-4930-9786-275bf6bf1988.png)

2022-10-11 19:15 UTC, naveenccmsd commented
> Tested latest, works fine. I believe currently only black icons are supported.

No,  Try chnaging system as dark mode.

In Light theme mode icon color is grey/black  and background is accent color whereas in dark mode icon color is accent color and background is greay/black

Please find sample.

![photo_2022-10-11_02-04-55](https://user-images.githubusercontent.com/7315975/195179221-e798e308-31e0-4dbc-8178-19c5600636dd.jpg)
![photo_2022-10-11_02-04-55 (2)](https://user-images.githubusercontent.com/7315975/195179230-95edeba4-0e0a-425e-addf-a45e0184371b.jpg)

2022-10-11 19:29 UTC, Creation2283 commented
Works fine, but idk why clock's icon still has a background 
![IMG_20221012_005713](https://user-images.githubusercontent.com/87919051/195181552-4df03c33-ddea-407b-82b4-3be7cc749c42.jpg)
@naveenccmsd

2022-10-11 20:01 UTC, naveenccmsd commented
Because it's dynamic icon from lawnchair override, let me see if this can fixed.

2022-10-11 20:46 UTC, yasandev commented
Thank you for contributing to Lawnchair. If the PR is not ready for review for now, please convert it to a draft PR as it's currently a bit confusing if we are supposed to review it yet or not.

2022-10-11 21:24 UTC, naveenccmsd commented
@yasandev , Sorry , I didn't noticed the clock icon didn't removed the bg as I don't  have it . It's fixed now.
Please review.

2022-10-11 21:25 UTC, naveenccmsd commented
![Screenshot_20221012-025443_Lawnchair](https://user-images.githubusercontent.com/7315975/195201313-0cb877b1-cf33-46af-a822-ca9ef1f7fbc0.jpg)

This will be like this after change

2022-10-12 02:20 UTC, Goooler requested changes
Changes in platform_frameworks_libs_systemui need to be split to a new PR in https://github.com/LawnchairLauncher/platform_frameworks_libs_systemui

2022-10-12 06:37 UTC, naveenccmsd commented
@Goooler created new PR 

https://github.com/LawnchairLauncher/platform_frameworks_libs_systemui/pull/7

2022-10-12 11:57 UTC, Goooler commented
@naveenccmsd Please update submodule to https://github.com/LawnchairLauncher/platform_frameworks_libs_systemui/commit/b8244916420ff8e49382d75637e31353212c24a7.

2022-10-12 12:00 UTC, yasandev commented
Not sure how you included the actual submodule file changes on this PR, but the submodule change on this PR should only be the target commit being changed as @Goooler just noted.

2022-10-12 12:06 UTC, Goooler approved these changes

2022-10-12 12:11 UTC, Goooler commented
Synced, wait for other reviewers.

2022-10-12 12:19 UTC, yasandev requested changes

2022-10-12 12:19 UTC, yasandev commented on lawnchair/res/values/strings.xml
> +    <string name="transparent_background_icons_description">Icon color might updated to match with background in Light Theme</string>
```suggestion
    <string name="transparent_background_icons">Transparent Themed Icons</string>
    <string name="transparent_background_icons_description">Use transparent background on themed icons</string>
```

These strings can be more clear.

2022-10-12 12:20 UTC, yasandev commented
Also, it would probably be better if the preference included "ThemedIcons" in its name as it would avoid confusion in the future.

2022-10-12 12:23 UTC, naveenccmsd commented
> Synced, wait for other reviewers.

Did I messed up  ? I still see submodule  changes in the PR.

2022-10-12 12:52 UTC, Goooler commented
Nope, the git parent repo just points a commit to the submodule.

2022-10-12 12:52 UTC, yasandev approved these changes

2022-10-12 12:55 UTC, merged