Cleanup exception catching under lawnchair
Deletescape-Media/Lawnchair pull request #3065
Opened 2022-10-30 13:31 UTC by Goooler

## Description

Follow up https://github.com/LawnchairLauncher/lawnchair/pull/3049#discussion_r1002692600

## Type of change

:white_check_mark: General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
:x: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

2022-10-30 15:23 UTC, yasandev commented
I'm not that familiar with `runCatching`, but isn't this bad practice? It looks like it just catches any exception and it's bad practice to just catch all exceptions. It's always better to catch specific exceptions, that's why multiple different exceptions are caught in some of the original code.

Other than the syntax improvement, this doesn't look like a positive change.

Only a few of the original catches catch all exceptions. Maybe we should just update those few.

2022-10-30 15:24 UTC, yasandev requested changes
I'm not that familiar with `runCatching`, but isn't this bad practice? It looks like it just catches any exception and it's bad practice to just catch all exceptions. It's always better to catch specific exceptions, that's why multiple different exceptions are caught in some of the original code.

Other than the syntax improvement, this doesn't look like a positive change.

Only a few of the original catches catch all exceptions. Maybe we should just update those few.

2022-10-31 01:56 UTC, Goooler commented
I think so, I'm reverting those changes now.

2022-10-31 05:48 UTC, yasandev approved these changes

2022-10-31 05:49 UTC, merged