Dock widget provider support
Deletescape-Media/Lawnchair pull request #3108
Opened 2022-11-13 06:43 UTC by yasandev

## Description

Adds the option to change the custom Lawnchair dock widget with the Google search widget (from the Google app). 

- Dock widget provider is called `HotseatMode` in the code.
- Resets back to LawnchairHotseat mode automatically if the selected mode is no longer available e.g. google app getting uninstalled or disabled.
- `hotseatQsb` boolean preference is now removed. To disable the search bar the user can select `HotseatMode.Disabled` on `hotseatMode`.

While this only gives the users 2 options, it's now possible to easily add new widget styles/providers for the dock. We can also look into allowing any widget to be shown on the dock in the future.

![hotseat-mode-selection](https://user-images.githubusercontent.com/41836211/201509251-d25c86ca-2ab0-43a9-b425-bb137f6998c8.gif)

## Type of change

:x: General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

2022-11-13 06:53 UTC, Goooler approved these changes
Love it!

2022-11-13 09:11 UTC, SuperDragonXD requested changes
Nice PR! Have a few UI changes in mind.

2022-11-13 09:11 UTC, SuperDragonXD commented on lawnchair/res/values/strings.xml
> +    <string name="hotseat_mode_google_search">Google Search Bar</string>
```suggestion
      <string name="hotseat_mode_disabled">Disabled</string>
      <string name="hotseat_mode_lawnchair">Lawnchair</string>
      <string name="hotseat_mode_google_search">Google Search Bar</string>

```

2022-11-13 09:11 UTC, SuperDragonXD commented on lawnchair/res/values/strings.xml
> +    <string name="hotseat_mode_label">Widget Provider</string>
Now that I think about it, I'd suggest changing this to a more precise label, like `Search Bar Widget`.

If you use this name, rename the other `Search Provider` string to `Search Engine` to prevent confusion.

2022-11-13 09:11 UTC, SuperDragonXD commented on lawnchair/src/app/lawnchair/ui/preferences/DockPreferences.kt
> +            PreferenceGroup(heading = stringResource(id = R.string.search_bar_label)) {
I'd suggest doing this UI:
```
// If Lawnchair is chosen
Search Bar
  Widget Provider
  Apply Accent Color -o
  Corner Radius
  Search Provider

// Otherwise
Search Bar
  Widget Provider
```

2022-11-13 14:25 UTC, Tropix126 commented
Just an observation, would it be a good idea to add a "customize" menu action when touching and holding on the widget?

https://user-images.githubusercontent.com/42101043/201526856-7ab58db2-b85f-4ff1-9036-142efd7380c1.mp4

2022-11-14 01:40 UTC, Goooler commented on lawnchair/res/values/strings.xml
> +    <string name="hotseat_mode_google_search">Google Search Bar</string>
Indent style change?

2022-11-14 01:52 UTC, SuperDragonXD commented on lawnchair/res/values/strings.xml
> +    <string name="hotseat_mode_google_search">Google Search Bar</string>
Yes, to better group the strings together.

2022-11-14 01:54 UTC, Goooler commented on lawnchair/res/values/strings.xml
> +    <string name="hotseat_mode_label">Widget Provider</string>
Alright, I've just set the default indent style to space f578bf5286125ef271b035ef2708d0add72f4d01.

2022-11-14 01:54 UTC, Goooler commented on lawnchair/res/values/strings.xml
> +    <string name="hotseat_mode_google_search">Google Search Bar</string>
Alright, I've just set the default indent style to space f578bf5286125ef271b035ef2708d0add72f4d01.

2022-11-14 06:50 UTC, yasandev commented on lawnchair/res/values/strings.xml
> +    <string name="hotseat_mode_google_search">Google Search Bar</string>
This indent is not a standard way of formatting strings and has already caused lots of annoyance when changing anything in the string files. And the main reason for having strings in resources is to be able to reuse them which makes grouping them by the screen meaningless.

2022-11-14 06:51 UTC, yasandev commented on lawnchair/res/values/strings.xml
> +    <string name="hotseat_mode_label">Widget Provider</string>
Yeah "Search Bar Widget" sounds more clear. Ill replace it.

2022-11-14 10:33 UTC, SuperDragonXD commented on lawnchair/res/values/strings.xml
> +    <string name="hotseat_mode_google_search">Google Search Bar</string>
Okay. I'll try to re-organize them by category (e.g. Dock strings on one area, Smartspace screens on another), instead of where it appears on screen.

2022-11-14 10:35 UTC, SuperDragonXD approved these changes

2022-11-14 11:27 UTC, merged