Add Support Gesture for A13
Deletescape-Media/Lawnchair pull request #3159
Opened 2022-12-10 08:06 UTC by MrSluffy

## Description

* Add Support Gesture for A13 without dropping A12/A12L
* Add support Icon (TaskIconCache)

Bug :
* PIP
* Split Screen

Added : ISplitScreenExt for A13 there's a better way to hook onGoingToRecentsLegacy but since I'm lazy I'll leave it to you guys :) Maybe you can clean it up :)

2022-12-10 09:21 UTC, azamuku commented
Also classic crash when you interact with widgets
https://paste.evolution-x.org/pjtcBR

2022-12-10 09:48 UTC, wolf-yuan-6115 commented
What is this PR for 🤔
I'm not maintainer, I just saw this PR and it looks a little bit crazy...

Huge changes in single commit, no further information for this pull request and probably introduced more issues.

2022-12-11 04:52 UTC, Goooler requested changes

2022-12-11 04:52 UTC, Goooler commented on SystemUIShared/build.gradle
> +    implementation project(path: ':hidden-api')
```suggestion
    implementation projects.hiddenApi
```

2022-12-11 04:52 UTC, Goooler commented on SystemUIShared/src/com/android/systemui/shared/system/ActivityManagerWrapper.java
> +
```suggestion
```

2022-12-11 04:52 UTC, Goooler commented on SystemUIShared/src/com/android/systemui/shared/system/PackageManagerWrapper.java
> +//import android.content.pm.IPackageManagerExt;
?

2022-12-11 04:52 UTC, Goooler commented on SystemUIShared/src/com/android/systemui/shared/system/PackageManagerWrapper.java
> +            intent.resolveTypeIfNeeded(AppGlobals.getInitialApplication().getContentResolver());
Do not leave unrelated changes here.

2022-12-11 04:52 UTC, Goooler commented on SystemUIShared/src/com/android/systemui/shared/system/PackageManagerWrapper.java
> +                intent, resolvedType, flags, UserHandle.getCallingUserId());
Same as above.

2022-12-11 04:57 UTC, Goooler commented
You should revert all unrelated format changes.

2022-12-11 05:33 UTC, closed without merging

2022-12-11 05:44 UTC, MrSluffy commented
Will pr new, include fix for pip and splitscreen so will be one pr