Mark more components exported
Deletescape-Media/Lawnchair pull request #3401
Opened 2023-03-28 09:44 UTC by Goooler

## Description

Some components hadn't been declared `android:exported` in manifest.

## Type of change

:white_check_mark: General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
:x: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

2023-03-28 09:59 UTC, liu-wanshun approved these changes

2023-03-28 09:59 UTC, liu-wanshun approved these changes

2023-03-28 11:19 UTC, suphon-t commented
Why though?

2023-03-28 13:34 UTC, Goooler commented
Android 12 requires all components to be declared `android:exported`, I just exported `RecentsActivity` as true.

2023-03-29 02:19 UTC, suphon-t commented
What I was wondering was why should `RecentsActivity` and `SlicePermissionActivity` be exported?

2023-03-29 02:25 UTC, Goooler commented
- Typo in `SlicePermissionActivity`'s config, it should not be exported.
- I'm not sure `RecentsActivity` should be exported or not.

Alright, just disable both of them.

2023-03-29 03:08 UTC, liu-wanshun requested changes

2023-03-29 03:08 UTC, liu-wanshun commented on quickstep/AndroidManifest.xml
RecentsActivity should exported true.

framework determines which APK provides Recents based on this component.

when the framework specifies this component as Recents , if the default Launcher is not this APK,Recents is this activity;if the default Launcher is this APK,LawnchairLauncher is this activity

2023-03-29 03:10 UTC, liu-wanshun commented on quickstep/AndroidManifest.xml
when the framework specifies this component as Recents , if the default Launcher is not this APK,Recents is this activity;if the default Launcher is this APK,Recents is LawnchairLauncher

2023-03-31 07:48 UTC, Goooler commented
https://developer.android.com/about/versions/12/behavior-changes-12#exported

> If your app targets Android 12 or higher and contains activities, services, or broadcast receivers that use intent filters, you must explicitly declare the android:exported attribute for these app components.

2023-03-31 07:48 UTC, closed without merging