Fixes for Android 9 issue #3778
Deletescape-Media/Lawnchair pull request #3808
Opened 2023-12-01 05:18 UTC by Rafael2616

## Description

Fixes #(issue) 

## Type of change

:x: General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
:x: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

2023-12-01 06:05 UTC, MrSluffy commented
There's some crashes still 

```
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/internal/policy/ScreenDecorationsUtils;
	at com.android.systemui.shared.system.QuickStepContract.supportsRoundedCornersOnWindows(QuickStepContract.java:384)
	at app.lawnchair.util.LawnchairUtilsKt.supportsRoundedCornersOnWindows(LawnchairUtils.kt:127)
	at com.android.quickstep.util.TaskCornerRadius.get(TaskCornerRadius.java:30)
	at com.android.quickstep.views.TaskView$FullscreenDrawParams.<init>(TaskView.java:1773)
	at com.android.quickstep.views.TaskView.<init>(TaskView.java:431)
	at com.android.quickstep.views.TaskView.<init>(TaskView.java:422)
	at com.android.quickstep.views.TaskView.<init>(TaskView.java:418)
	... 12 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.policy.ScreenDecorationsUtils" on path: DexPathList[[zip file "/data/app/app.lawnchair.debug-2IYx9NyOOjIFsbEGavGNSw==/base.apk"],nativeLibraryDirectories=[/data/app/app.lawnchair.debug-2IYx9NyOOjIFsbEGavGNSw==/lib/arm, /data/app/app.lawnchair.debug-2IYx9NyOOjIFsbEGavGNSw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

You can try add condition here atleastq too [`supportsRoundedCornersOnWindows`](https://github.com/LawnchairLauncher/lawnchair/blob/13-dev/lawnchair/src/app/lawnchair/util/LawnchairUtils.kt#L123)

2023-12-01 06:12 UTC, Rafael2616 commented
> There's some crashes still 
> 
> ```
> Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/internal/policy/ScreenDecorationsUtils;
> 	at com.android.systemui.shared.system.QuickStepContract.supportsRoundedCornersOnWindows(QuickStepContract.java:384)
> 	at app.lawnchair.util.LawnchairUtilsKt.supportsRoundedCornersOnWindows(LawnchairUtils.kt:127)
> 	at com.android.quickstep.util.TaskCornerRadius.get(TaskCornerRadius.java:30)
> 	at com.android.quickstep.views.TaskView$FullscreenDrawParams.<init>(TaskView.java:1773)
> 	at com.android.quickstep.views.TaskView.<init>(TaskView.java:431)
> 	at com.android.quickstep.views.TaskView.<init>(TaskView.java:422)
> 	at com.android.quickstep.views.TaskView.<init>(TaskView.java:418)
> 	... 12 more
> Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.policy.ScreenDecorationsUtils" on path: DexPathList[[zip file "/data/app/app.lawnchair.debug-2IYx9NyOOjIFsbEGavGNSw==/base.apk"],nativeLibraryDirectories=[/data/app/app.lawnchair.debug-2IYx9NyOOjIFsbEGavGNSw==/lib/arm, /data/app/app.lawnchair.debug-2IYx9NyOOjIFsbEGavGNSw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]
> 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> ```
> 
> You can try add condition here atleastq too [`supportsRoundedCornersOnWindows`](https://github.com/LawnchairLauncher/lawnchair/blob/13-dev/lawnchair/src/app/lawnchair/util/LawnchairUtils.kt#L123)

Wow, that was a good start, 3 problems fixed with the same fix. My record

2023-12-01 06:13 UTC, Rafael2616 commented
What value should I put here for below Q, true or false?

```
    return QuickStepContract.supportsRoundedCornersOnWindows(context.resources)

```

2023-12-01 06:18 UTC, MrSluffy commented
> What value should I put here for below Q, true or false?
> 
> ```
>     return QuickStepContract.supportsRoundedCornersOnWindows(context.resources)
> ```

false

2023-12-01 06:25 UTC, Rafael2616 commented
> > What value should I put here for below Q, true or false?
> > 
> > ```
> >     return QuickStepContract.supportsRoundedCornersOnWindows(context.resources)
> > ```
> 
> false
> 

Done 👍

2023-12-01 06:40 UTC, MrSluffy commented
> > > What value should I put here for below Q, true or false?
> > > ```
> > >     return QuickStepContract.supportsRoundedCornersOnWindows(context.resources)
> > > ```
> > 
> > 
> > false
> 
> Done 👍

No, use this intead and test it
```
fun getWindowCornerRadius(context: Context): Float {
    val prefs = getPrefsIfUnlocked(context)
    return when {
        prefs?.overrideWindowCornerRadius?.get() == true -> prefs.windowCornerRadius.get().toFloat()
        Utilities.ATLEAST_Q -> QuickStepContract.getWindowCornerRadius(context)
        else -> 0.0f
    }
}
```

2023-12-01 06:44 UTC, Rafael2616 commented
Sorry, I changed the wrong function

2023-12-01 06:44 UTC, Rafael2616 commented
I will correct it now

2023-12-01 06:49 UTC, Rafael2616 commented
Done again

2023-12-01 06:49 UTC, MrSluffy commented
after build you can test

2023-12-01 06:53 UTC, MrSluffy commented
> Done again

this too : 

```
fun supportsRoundedCornersOnWindows(context: Context): Boolean {
    val prefs = getPrefsIfUnlocked(context)

    return when {
        prefs?.overrideWindowCornerRadius?.get() == true -> true
        Utilities.ATLEAST_Q -> QuickStepContract.supportsRoundedCornersOnWindows(context.resources)
        else -> false
    }
}
```

2023-12-01 06:57 UTC, Rafael2616 commented
These other problem appeared
I'll continue tomorrow, as it's already late here

```
Lawnchair (Debug) bug report 1 de dez de 2023 03:55:47
version: 13 Dev (#2463) (13)
commit: 29f8a36
build.brand: lge
build.device: mmh4
build.display: PKQ1.190522.001
build.fingerprint: lge/mmh4_f/mmh4:9/PKQ1.190522.001/2106722188f70:user/release-keys
build.hardware: mmh4
build.id: PKQ1.190522.001
build.manufacturer: LGE
build.model: LM-X420
build.security.level: 2021-03-01
build.product: mmh4_f
build.type: user
version.codename: REL
version.incremental: 2106722188f70
version.release: 9
version.sdk_int: 28
display.density_dpi: 280
isRecentsEnabled: false

error: Uncaught exception

java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/ISystemGestureExclusionListener$Stub;
	at com.android.quickstep.RecentsAnimationDeviceState.<init>(RecentsAnimationDeviceState.java:158)
	at com.android.quickstep.RecentsAnimationDeviceState.<init>(RecentsAnimationDeviceState.java:129)
	at com.android.quickstep.util.SplitWithKeyboardShortcutController.<init>(SplitWithKeyboardShortcutController.java:72)
	at com.android.launcher3.uioverrides.QuickstepLauncher.setupViews(QuickstepLauncher.java:230)
	at app.lawnchair.LawnchairLauncher.setupViews(LawnchairLauncher.kt:272)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:518)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:527)
	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:208)
	at android.app.Activity.performCreate(Activity.java:7159)
	at android.app.Activity.performCreate(Activity.java:7150)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3001)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3156)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6993)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.ISystemGestureExclusionListener$Stub" on path: DexPathList[[zip file "/data/app/app.lawnchair.debug-tmKROEOpm8nsss04spYktQ==/base.apk"],nativeLibraryDirectories=[/data/app/app.lawnchair.debug-tmKROEOpm8nsss04spYktQ==/lib/arm, /data/app/app.lawnchair.debug-tmKROEOpm8nsss04spYktQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 23 more

```

2023-12-01 13:20 UTC, Rafael2616 commented
> These other problem appeared
> I'll continue tomorrow, as it's already late here
> 
> ```
> Lawnchair (Debug) bug report 1 de dez de 2023 03:55:47
> version: 13 Dev (#2463) (13)
> commit: 29f8a36
> build.brand: lge
> build.device: mmh4
> build.display: PKQ1.190522.001
> build.fingerprint: lge/mmh4_f/mmh4:9/PKQ1.190522.001/2106722188f70:user/release-keys
> build.hardware: mmh4
> build.id: PKQ1.190522.001
> build.manufacturer: LGE
> build.model: LM-X420
> build.security.level: 2021-03-01
> build.product: mmh4_f
> build.type: user
> version.codename: REL
> version.incremental: 2106722188f70
> version.release: 9
> version.sdk_int: 28
> display.density_dpi: 280
> isRecentsEnabled: false
> 
> error: Uncaught exception
> 
> java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/ISystemGestureExclusionListener$Stub;
> 	at com.android.quickstep.RecentsAnimationDeviceState.<init>(RecentsAnimationDeviceState.java:158)
> 	at com.android.quickstep.RecentsAnimationDeviceState.<init>(RecentsAnimationDeviceState.java:129)
> 	at com.android.quickstep.util.SplitWithKeyboardShortcutController.<init>(SplitWithKeyboardShortcutController.java:72)
> 	at com.android.launcher3.uioverrides.QuickstepLauncher.setupViews(QuickstepLauncher.java:230)
> 	at app.lawnchair.LawnchairLauncher.setupViews(LawnchairLauncher.kt:272)
> 	at com.android.launcher3.Launcher.onCreate(Launcher.java:518)
> 	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:527)
> 	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:208)
> 	at android.app.Activity.performCreate(Activity.java:7159)
> 	at android.app.Activity.performCreate(Activity.java:7150)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3001)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3156)
> 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
> 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loop(Looper.java:205)
> 	at android.app.ActivityThread.main(ActivityThread.java:6993)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
> Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.ISystemGestureExclusionListener$Stub" on path: DexPathList[[zip file "/data/app/app.lawnchair.debug-tmKROEOpm8nsss04spYktQ==/base.apk"],nativeLibraryDirectories=[/data/app/app.lawnchair.debug-tmKROEOpm8nsss04spYktQ==/lib/arm, /data/app/app.lawnchair.debug-tmKROEOpm8nsss04spYktQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]
> 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> 	... 23 more
> 
> ```

This error happens because this method is not supported on Android 9 and below, but I'm not sure how to override this

```
android.view.ISystemGestureExclusionListener
```

He is called in this class

https://github.com/LawnchairLauncher/lawnchair/blob/4402ef1bf3722a4f203f0bc93f1851926af1712e/quickstep/src/com/android/quickstep/RecentsAnimationDeviceState.java#L158

Defined here:

https://github.com/LawnchairLauncher/lawnchair/blob/4402ef1bf3722a4f203f0bc93f1851926af1712e/systemUIShared/src/com/android/systemui/shared/system/SystemGestureExclusionListenerCompat.java#L33

2023-12-01 16:35 UTC, Rafael2616 commented
I limited this function to Android 10 +, maybe it will work now

2023-12-01 23:59 UTC, Rafael2616 commented
@MrSluffy Can you review my last commit and run it if it's correct, so I can see if there are any more problems launching the app?

2023-12-02 00:11 UTC, MrSluffy commented
> Author

I can't test right now, but looks fine to me, test it now

2023-12-02 00:13 UTC, Rafael2616 commented
ok, I just need you to run the workflow when you can

2023-12-02 00:29 UTC, Rafael2616 commented
More one:

```
Lawnchair (Debug) bug report 1 de dez de 2023 21:26:18
version: 13 Dev (#2478) (13)
commit: 195618a
build.brand: lge
build.device: mmh4
build.display: PKQ1.190522.001
build.fingerprint: lge/mmh4_f/mmh4:9/PKQ1.190522.001/2106722188f70:user/release-keys
build.hardware: mmh4
build.id: PKQ1.190522.001
build.manufacturer: LGE
build.model: LM-X420
build.security.level: 2021-03-01
build.product: mmh4_f
build.type: user
version.codename: REL
version.incremental: 2106722188f70
version.release: 9
version.sdk_int: 28
display.density_dpi: 280
isRecentsEnabled: false

error: Uncaught exception

java.lang.RuntimeException: Unable to start activity ComponentInfo{app.lawnchair.debug/app.lawnchair.LawnchairLauncher}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.systemui.shared.system.SystemGestureExclusionListenerCompat.unregister()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3021)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3156)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6993)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.systemui.shared.system.SystemGestureExclusionListenerCompat.unregister()' on a null object reference
	at com.android.quickstep.RecentsAnimationDeviceState.onDisplayInfoChanged(RecentsAnimationDeviceState.java:266)
	at com.android.quickstep.RecentsAnimationDeviceState.<init>(RecentsAnimationDeviceState.java:176)
	at com.android.quickstep.RecentsAnimationDeviceState.<init>(RecentsAnimationDeviceState.java:129)
	at com.android.quickstep.util.SplitWithKeyboardShortcutController.<init>(SplitWithKeyboardShortcutController.java:72)
	at com.android.launcher3.uioverrides.QuickstepLauncher.setupViews(QuickstepLauncher.java:230)
	at app.lawnchair.LawnchairLauncher.setupViews(LawnchairLauncher.kt:272)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:518)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:527)
	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:208)
	at android.app.Activity.performCreate(Activity.java:7159)
	at android.app.Activity.performCreate(Activity.java:7150)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3001)
	... 11 more

```

2023-12-02 00:54 UTC, Rafael2616 commented
I added a null check, since the last commit made this `mExclusionListener` null, since it was not initialized (because it is also not supported)

2023-12-02 14:29 UTC, Rafael2616 commented
I forgot `;` 🫥

2023-12-03 00:24 UTC, Rafael2616 commented
I fixed one more problem, now I'm in this

```
Lawnchair (Debug) bug report 2 de dez de 2023 21:21:32
version: 13 Dev (#9) (13)
commit: ee9e679
build.brand: lge
build.device: mmh4
build.display: PKQ1.190522.001
build.fingerprint: lge/mmh4_f/mmh4:9/PKQ1.190522.001/2106722188f70:user/release-keys
build.hardware: mmh4
build.id: PKQ1.190522.001
build.manufacturer: LGE
build.model: LM-X420
build.security.level: 2021-03-01
build.product: mmh4_f
build.type: user
version.codename: REL
version.incremental: 2106722188f70
version.release: 9
version.sdk_int: 28
display.density_dpi: 280
isRecentsEnabled: false

error: Uncaught exception

java.lang.NoSuchMethodError: No virtual method getSourceLayoutResId()I in class Landroid/view/View; or its super classes (declaration of 'android.view.View' appears in /system/framework/framework.jar!classes2.dex)
	at com.android.launcher3.Workspace.setPageIndicatorInset(Workspace.java:412)
	at com.android.launcher3.Workspace.setInsets(Workspace.java:365)
	at com.android.launcher3.InsettableFrameLayout.setFrameLayoutChildInsets(InsettableFrameLayout.java:29)
	at com.android.launcher3.InsettableFrameLayout.setInsets(InsettableFrameLayout.java:44)
	at com.android.launcher3.InsettableFrameLayout.setFrameLayoutChildInsets(InsettableFrameLayout.java:29)
	at com.android.launcher3.InsettableFrameLayout.setInsets(InsettableFrameLayout.java:44)
	at com.android.launcher3.LauncherRootView.dispatchInsets(LauncherRootView.java:87)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:555)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:527)
	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:208)
	at android.app.Activity.performCreate(Activity.java:7159)
	at android.app.Activity.performCreate(Activity.java:7150)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3001)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3156)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6993)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)

```

2023-12-03 00:25 UTC, Rafael2616 commented
I'm also running this on my GitHub Actions

2023-12-03 00:57 UTC, Rafael2616 commented
Related to the above error:

It looks like 'getSourceLayoutResId' It didn't work below 10, analyzing the code I saw that this has already been addressed elsewhere but not here

https://github.com/LawnchairLauncher/lawnchair/blob/13-dev/src%2Fcom%2Fandroid%2Flauncher3%2FWorkspace.java

2023-12-03 01:06 UTC, Rafael2616 commented
Can I simply check what the version is and set a value if it is below 10? If yes, what value, false or true?

2023-12-03 02:40 UTC, Rafael2616 commented
New problem, resource not found 

`android.R.color.system_accent3_200 `

```
Lawnchair (Debug) bug report 2 de dez de 2023 23:12:32
version: 13 Dev (#12) (13)
commit: efc4841
build.brand: lge
build.device: mmh4
build.display: PKQ1.190522.001
build.fingerprint: lge/mmh4_f/mmh4:9/PKQ1.190522.001/2106722188f70:user/release-keys
build.hardware: mmh4
build.id: PKQ1.190522.001
build.manufacturer: LGE
build.model: LM-X420
build.security.level: 2021-03-01
build.product: mmh4_f
build.type: user
version.codename: REL
version.incremental: 2106722188f70
version.release: 9
version.sdk_int: 28
display.density_dpi: 280
isRecentsEnabled: false

error: Uncaught exception

android.content.res.Resources$NotFoundException: Resource ID #0x1060055
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:230)
	at android.content.res.Resources.getColor(Resources.java:964)
	at com.android.launcher3.BubbleTextView.applyIconAndLabel(BubbleTextView.java:396)
	at com.android.launcher3.BubbleTextView.applyFromWorkspaceItem(BubbleTextView.java:347)
	at com.android.launcher3.BubbleTextView.applyFromWorkspaceItem(BubbleTextView.java:317)
	at com.android.launcher3.BubbleTextView.applyFromWorkspaceItem(BubbleTextView.java:312)
	at com.android.launcher3.Launcher.createShortcut(Launcher.java:1430)
	at com.android.launcher3.Launcher.createShortcut(Launcher.java:1415)
	at com.android.launcher3.Launcher.bindItems(Launcher.java:2525)
	at com.android.launcher3.Launcher.bindItems(Launcher.java:2486)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder.lambda$bindWorkspaceItems$7(BaseLauncherBinder.java:331)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder$$ExternalSyntheticLambda10.execute(Unknown Source:6)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder.lambda$executeCallbacksTask$9(BaseLauncherBinder.java:352)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder.$r8$lambda$a4Qxm57bpz83-gfmBrdCLjV8bf4(Unknown Source:0)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder$$ExternalSyntheticLambda9.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6993)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)

```

2023-12-03 03:34 UTC, Rafael2616 commented
Ok, this is the newest problem and I don't know how to solve it
The method 'viewRootImpl.getSurfaceControl()' It's not available on Android 9 and I don't know how to replace it here 

```
private void onLauncherDraw() {
        View view = mLauncher.getDragLayer();
        ViewRootImpl viewRootImpl = view.getViewRootImpl();
        setSurface(viewRootImpl != null ? viewRootImpl.getSurfaceControl() : null);
        view.post(() -> view.getViewTreeObserver().removeOnDrawListener(mOnDrawListener));
    }

```

2023-12-03 04:14 UTC, Rafael2616 commented
I did it, now it works 🎉🎉😅

2023-12-03 04:14 UTC, Rafael2616 commented
![Screenshot_20231203-011441.png](https://github.com/LawnchairLauncher/lawnchair/assets/93414086/edd75789-79a0-4ae0-8477-345ae46f0504)

2023-12-03 04:15 UTC, Rafael2616 commented
![Screenshot_20231203-011448.png](https://github.com/LawnchairLauncher/lawnchair/assets/93414086/0a06d8ce-bddd-485b-a473-1e5e2f6099fe)

2023-12-03 04:20 UTC, Rafael2616 commented
No very obvious crashes so far, in fact, no crashes at all, just the Doxk search window that is full. But it works

2023-12-03 05:12 UTC, MrSluffy requested changes

2023-12-03 05:12 UTC, MrSluffy commented on quickstep/src/com/android/launcher3/statehandlers/DepthController.java
> +}
Clean up, don't add unneccsary spacing

2023-12-03 05:12 UTC, MrSluffy commented on quickstep/src/com/android/quickstep/RecentsAnimationDeviceState.java
> +
this too

2023-12-03 05:12 UTC, MrSluffy commented on quickstep/src/com/android/quickstep/RecentsAnimationDeviceState.java
> +            if (mExclusionListener == null) {
`if (mExclusionListener == null) return`

2023-12-03 05:12 UTC, MrSluffy commented on src/com/android/launcher3/BubbleTextView.java
> +                .getColor(mColor, getContext().getTheme());
```
mDotParams.color = iconDrawable.getIconColor();
```

2023-12-03 05:12 UTC, MrSluffy commented on src/com/android/launcher3/BubbleTextView.java
> +        if (Utilities.ATLEAST_Q) {
remove this

2023-12-03 05:12 UTC, MrSluffy commented on quickstep/src/com/android/quickstep/RecentsAnimationDeviceState.java
> +               mPipIsActive = false;
this too

2023-12-03 05:12 UTC, MrSluffy commented on quickstep/src/com/android/launcher3/statehandlers/DepthController.java
> +            Bitmap bitmap = view.getDrawingCache();
why do we need this? exactly?

2023-12-03 06:42 UTC, MrSluffy commented
> No very obvious crashes so far, in fact, no crashes at all, Only the dock search bar is squeezed. But it works

Great, I pushed some changes, kindly test once build, 

and for the tight dock, it will be fix in diff since there's already open issue about it

2023-12-03 09:44 UTC, suphon-t commented on src/com/android/launcher3/BubbleTextView.java
> +        mDotParams.color = iconDrawable.getIconColor();
Lawnchair has a color theming system for these dynamic colors. Please add accent3_200 [here](https://github.com/LawnchairLauncher/lawnchair/blob/13-dev/lawnchair/src/app/lawnchair/theme/color/ColorTokens.kt) and use it instead.

2023-12-03 09:44 UTC, suphon-t commented on lawnchair/res/values-v28/colors.xml
> +    <color name="system_accent1_100">@android:color/transparent</color>
Please use something more appropriate than transparent. This can cause visual glitches or even crashes in some places.

2023-12-06 02:47 UTC, MrSluffy commented
I revert the merged as it messes with the commit change

2023-12-06 02:51 UTC, Rafael2616 commented
Ok

2023-12-06 02:53 UTC, Rafael2616 commented
Could you see that

https://github.com/LawnchairLauncher/lawnchair/pull/3808#discussion_r1412912415

2023-12-06 02:55 UTC, Rafael2616 commented
And Here

https://github.com/LawnchairLauncher/lawnchair/pull/3808#discussion_r1413083124

2023-12-06 02:57 UTC, Rafael2616 commented
How to solve this after applying @suphon-t suggestion

/home/runner/work/lawnchair/lawnchair/src/com/android/launcher3/BubbleTextView.java:396: error: Accent3_200 has private access in ColorTokens

2023-12-06 03:05 UTC, Rafael2616 commented
Thanks

2023-12-06 03:11 UTC, Rafael2616 commented
It still works 👍. it needs only my 2 review comments above so it's ready to merge

2023-12-06 03:36 UTC, Rafael2616 commented on quickstep/src/com/android/launcher3/statehandlers/DepthController.java
> +            Bitmap bitmap = view.getDrawingCache();
In fact it was the equivalent replacement that I found for the "setSurface" function with the method that is incompatible, I don't know if just leaving it without it will work.

2023-12-06 03:36 UTC, Rafael2616 commented on quickstep/src/com/android/launcher3/statehandlers/DepthController.java
> +            Bitmap bitmap = view.getDrawingCache();
> why do we need this? exactly?

And i also need to convert Bitmap to Canvas

2023-12-06 03:36 UTC, Rafael2616 commented on src/com/android/launcher3/BubbleTextView.java
> +                .getColor(mColor, getContext().getTheme());
This caused the app to crash again
```
Lawnchair (Debug) bug report 3 de dez de 2023 02:33:03
version: 13 Dev (#22) (13)
commit: 7c3c8d5
build.brand: lge
build.device: mmh4
build.display: PKQ1.190522.001
build.fingerprint: lge/mmh4_f/mmh4:9/PKQ1.190522.001/2106722188f70:user/release-keys
build.hardware: mmh4
build.id: PKQ1.190522.001
build.manufacturer: LGE
build.model: LM-X420
build.security.level: 2021-03-01
build.product: mmh4_f
build.type: user
version.codename: REL
version.incremental: 2106722188f70
version.release: 9
version.sdk_int: 28
display.density_dpi: 280
isRecentsEnabled: false

error: Uncaught exception

android.content.res.Resources$NotFoundException: Resource ID #0xff8ab1e7
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:230)
	at android.content.res.Resources.getColor(Resources.java:964)
	at com.android.launcher3.BubbleTextView.applyIconAndLabel(BubbleTextView.java:396)
	at com.android.launcher3.BubbleTextView.applyFromWorkspaceItem(BubbleTextView.java:347)
	at com.android.launcher3.BubbleTextView.applyFromWorkspaceItem(BubbleTextView.java:317)
	at com.android.launcher3.BubbleTextView.applyFromWorkspaceItem(BubbleTextView.java:312)
	at com.android.launcher3.Launcher.createShortcut(Launcher.java:1430)
	at com.android.launcher3.Launcher.createShortcut(Launcher.java:1415)
	at com.android.launcher3.Launcher.bindItems(Launcher.java:2525)
	at com.android.launcher3.Launcher.bindItems(Launcher.java:2486)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder.lambda$bindWorkspaceItems$7(BaseLauncherBinder.java:331)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder$$ExternalSyntheticLambda10.execute(Unknown Source:6)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder.lambda$executeCallbacksTask$9(BaseLauncherBinder.java:352)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder.$r8$lambda$a4Qxm57bpz83-gfmBrdCLjV8bf4(Unknown Source:0)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder$$ExternalSyntheticLambda9.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6993)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)

```

2023-12-06 03:36 UTC, Rafael2616 commented on lawnchair/res/values-v28/colors.xml
> +    <color name="system_accent1_100">@android:color/transparent</color>
What color would you think is appropriate as I'm just using the same solution as was used to fix crash on Android 10, 11 by @MrSluffy

2023-12-06 03:36 UTC, Rafael2616 commented on src/com/android/launcher3/BubbleTextView.java
> +        mDotParams.color = iconDrawable.getIconColor();
@MrSlufffy Could you do this?

2023-12-06 04:13 UTC, MrSluffy approved these changes

2023-12-06 16:51 UTC, Rafael2616 commented
I fixed this problem more, could you check 

https://github.com/LawnchairLauncher/lawnchair/assets/93414086/f2ee6219-f450-4453-bbd9-5672003930f0

2023-12-06 22:32 UTC, MrSluffy commented on systemUIShared/src/com/android/systemui/shared/system/ActivityManagerWrapper.java
> +    private ActivityManagerWrapper() {
this will cause issue in upper version

2023-12-06 22:32 UTC, MrSluffy commented on systemUIShared/src/com/android/systemui/shared/system/ActivityManagerWrapper.java
> +        mAtm = atleastQ ? ActivityTaskManager.getInstance() : null;
this too

2023-12-06 22:32 UTC, MrSluffy commented on systemUIShared/src/com/android/systemui/shared/system/ActivityManagerWrapper.java
> +        if (atleastQ) {
this too

2023-12-06 22:35 UTC, Rafael2616 commented on systemUIShared/src/com/android/systemui/shared/system/ActivityManagerWrapper.java
> +    private ActivityManagerWrapper() {
Okay, we don't want that to happen 😂. What must be done then to make it work in both?

2023-12-07 11:19 UTC, suphon-t commented on lawnchair/res/values-v28/colors.xml
> +    <color name="system_accent1_100">@android:color/transparent</color>
Let's leave it like this for now if you say it works

2023-12-09 00:23 UTC, Rafael2616 commented
@MrSluffy Could I just revert the last change so this can be merged and then fix this in a separate PR since it doesn't significantly affect usage? So much so that I only noticed it after 5 days of use. Or do you intend to correct it soon?

2023-12-09 00:37 UTC, MrSluffy commented
> @MrSluffy Could I just revert the last change so this can be merged and then fix this in a separate PR since it doesn't significantly affect usage? So much so that I only noticed it after 5 days of use. Or do you intend to correct it soon?

sure, I'll check it later

2023-12-09 00:44 UTC, Rafael2616 commented
I'll create an issue for this specific issue soon

2023-12-09 06:00 UTC, MrSluffy commented
I think the crash in `java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/ActivityTaskManager;` are similar with this 282edc72a65057821d65fc303e4e92ad99a3fec3 , it should work once merge

2023-12-09 06:05 UTC, merged

2023-12-09 10:49 UTC, Rafael2616 commented
> I think the crash in `java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/ActivityTaskManager;` are similar with this 282edc72a65057821d65fc303e4e92ad99a3fec3 , it should work once merge

Yes, this problem no longer occurred after the merge 👍