Add toggleable material u popup
Deletescape-Media/Lawnchair pull request #4034
Opened 2024-01-30 15:44 UTC by validcube

## Description

Add toggleable new material u popup, there are also unrelated changes like cleanup and grammaticla fix.

## Type of change

:x: General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
✅ New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-01-30 22:11 UTC, MrSluffy requested changes

2024-01-30 22:11 UTC, MrSluffy commented on src/com/android/launcher3/popup/PopupContainerWithArrow.java
> +        if (FeatureFlags.showMaterialUPopup(icon.getContext())) {
use `launcher` instead of `icon.getContext()`

2024-01-30 22:11 UTC, MrSluffy commented on quickstep/src/com/android/launcher3/taskbar/TaskbarPopupController.java
> +import android.content.Context;
remove this

2024-01-31 00:50 UTC, MrSluffy approved these changes

2024-01-31 00:51 UTC, merged

2024-02-08 14:33 UTC, Susexe commented
Don't you mean "Material UI"? There's a typo in translation string on Crowdin, too.

2024-02-08 15:06 UTC, validcube commented
> Don't you mean "Material UI"? There's a typo in the translation string on Crowdin, too.

"Material U" is not a typo despite it sounding like a typo. It's just another way of saying "Material You"

I guess using "Material You" would be correct because I think hardly anyone use the "Material U" spelling, but feel free to open an PR if you'd like.

2024-02-08 15:11 UTC, Susexe commented
Yeah, I realized minutes after sending the comment. It sounds very informal, so I should probably open a PR. Thanks.